package io.github.gwkit.coverjet.gradle.task

import org.gradle.api.Project
import org.gradle.api.provider.Provider
import org.gradle.api.tasks.TaskProvider
import org.gradle.api.tasks.WriteProperties

internal fun Project.generateTestKitProperties(
    testTaskName: String,
    javaAgentPropertyProvider: TaskProvider<CovJvmParameter>,
    configure: WriteProperties.() -> Unit,
): TaskProvider<WriteProperties> = tasks.register(
    "${testTaskName}TestKitProperties",
    WriteProperties::class.java,
) { task ->
    with(task) {
        group = "verification"
        description = "Generates gradle.properties with Intellij Coverage java agent jmv args"
        comment = "Generated by CoverJet Plugin"

        val testKitPropertiesFile = layout.buildDirectory.file("testkit/${testTaskName}-testkit-gradle.properties")
        destinationFile.set(testKitPropertiesFile)

        inputs.files(javaAgentPropertyProvider)

        val jvmArgs: Provider<String> = javaAgentPropertyProvider.readJavaAgentParameter()
            .map { it.joinToString(" ") }

        property("org.gradle.jvmargs", jvmArgs)

        configure()
    }
}
