package io.github.gwkit.coverjet.gradle.task

import io.github.gwkit.coverjet.gradle.provider.CovJvmArgumentsProvider
import org.gradle.api.Project
import org.gradle.api.tasks.TaskProvider
import org.gradle.api.tasks.WriteProperties

internal fun Project.generateTestKitProperties(
    testTaskName: String,
    jvmArgsProvider: CovJvmArgumentsProvider,
    configure: WriteProperties.() -> Unit,
): TaskProvider<WriteProperties> = tasks.register(
    "${testTaskName}TestKitProperties",
    WriteProperties::class.java,
) { task ->
    with(task) {
        group = "verification"
        description = "Generates gradle.properties with Intellij Coverage java agent jmv args"
        comment = "Generated by CoverJet Plugin"

        val testKitPropertiesFile = layout.buildDirectory.file("testkit/${testTaskName}-testkit-gradle.properties")
        destinationFile.set(testKitPropertiesFile)

        property(
            "org.gradle.jvmargs",
            provider {
                jvmArgsProvider.asArguments().joinToString(" ")
            }
        )

        configure()
    }
}
